version: '3'
services:
  blaze-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      TRUST_PROXY: 1
    ports:
      - 8038:3030

  blaze-client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 8037:80
    depends_on:
      - blaze-server